#### First API

##### Hecho con dataframes

In [132]:
import requests
import json

response = requests.get('https://api.fbi.gov/wanted/v1/list')
print("FBI Status Code:", response.status_code)
results = response.json()

FBI Status Code: 200

In [133]:
import pandas as pd
data = pd.DataFrame(results)
data.head()

   total                                              items  page
0    964  {'reward_text': 'The FBI is offering a reward ...     1
1    964  {'reward_text': 'The FBI is offering a reward ...     1
2    964  {'reward_text': None, 'aliases': ['Cristian Mo...     1
3    964  {'reward_text': None, 'aliases': ['James Von K...     1
4    964  {'reward_text': None, 'aliases': None, 'public...     1

In [134]:
data.shape

(20, 3)

In [135]:
from pandas import json_normalize

flattened_data = json_normalize(data['items'])

flattened_data.head()

,reward_text,aliases,publication,url,warning_message,age_max,additional_information,weight_min,height_min,field_offices,...,possible_states,eyes,subjects,languages,ncic,possible_countries,dates_of_birth_used,person_classification,race_raw,@id
0,"The FBI is offering a reward of up to $10,000 ...","[Chris Gardner, Christopher Charles Gardner]",2021-12-08T10:43:00,https://www.fbi.gov/wanted/wcc/christopher-c-g...,SHOULD BE CONSIDERED AN INTERNATIONAL FLIGHT R...,NaN,None,175.0,71.0,[milwaukee],...,None,blue,[White-Collar Crime],"[English, French, German]",W496951108,None,"[July 8, 1955, July 8, 1954]",Main,White,https://api.fbi.gov/@wanted-person/3f5d03cb681...
1,"The FBI is offering a reward of up to $5,000 f...",None,2022-04-06T11:46:00,https://www.fbi.gov/wanted/seeking-info/vandal...,None,NaN,None,NaN,NaN,[albuquerque],...,None,None,[Seeking Information],None,None,None,None,Main,None,https://api.fbi.gov/@wanted-person/11954299cdf...
2,None,"[Cristian Mora, ""C-Fresh"", ""Fresh""]",2022-04-15T07:34:00,https://www.fbi.gov/wanted/cei/cristian-rios-mora,SHOULD BE CONSIDERED ARMED AND DANGEROUS AND A...,NaN,None,210.0,71.0,[sanfrancisco],...,None,brown,"[Criminal Enterprise Investigations, Case of t...",None,None,None,"[November 2, 1992]",Main,White (Hispanic),https://api.fbi.gov/@wanted-person/616712ad0f2...
3,None,"[James Von Kirk, Juan Antonio Barroso, Jose A....",2010-08-27T17:55:00,https://www.fbi.gov/wanted/cac/jose-antonio-ba...,SHOULD BE CONSIDERED DANGEROUS AND AN ESCAPE RISK,NaN,None,150.0,67.0,[littlerock],...,"[US-AR, US-KS]",brown,[Crimes Against Children],None,W047103701,"[MEX, USA]","[January 10, 1973]",Main,White (Hispanic),https://api.fbi.gov/@wanted-person/f03b9a09ff0...
4,None,None,2022-04-01T09:21:00,https://www.fbi.gov/wanted/kidnap/katauna-nate...,None,NaN,None,150.0,63.0,[sanfrancisco],...,None,brown,"[Kidnappings and Missing Persons, Indian Country]",None,None,None,"[November 29, 2007]",Main,Native American,https://api.fbi.gov/@wanted-person/8224f8c3c83...

#### Second API

##### Hecho con json.loads

In [136]:
import requests
import json

response = requests.get('https://datos.madrid.es/egob/catalogo/205026-0-cementerios.json')
print("Cementerio Status Code:", response.status_code)

Cementerio Status Code: 200

In [137]:
# print(response.json())

In [138]:
data = json.loads(response.content)
# print(data['total'])
# print(data['items'][0]['title'])

In [139]:
# from pandas.io.json import json_normalize # DEPRECATED
from pandas import json_normalize

results = response.json()
flattened_data = json_normalize(data['@graph'])

flattened_data.drop("@id",axis=1,inplace=True)
flattened_data.drop("@type",axis=1,inplace=True)
flattened_data.drop("id",axis=1,inplace=True)

flattened_data.head()

,title,relation,address.district.@id,address.area.@id,address.locality,address.postal-code,address.street-address,location.latitude,location.longitude,organization.organization-desc,organization.accesibility,organization.schedule,organization.services,organization.organization-name
0,Cementerio Británico (British Cemetery),http://www.madrid.es/sites/v/index.jsp?vgnextc...,https://datos.madrid.es/egob/kos/Provincia/Mad...,https://datos.madrid.es/egob/kos/Provincia/Mad...,MADRID,28019,CALLE COMANDANTE FONTANES 7,40.395213,-3.722634,"Metro: Urgel (línea 5). Bus: 118, 119, 34, 35.",3,"Martes, jueves, sábados (excepto fiestas nacio...",,Cementerio Británico (British Cemetery)
1,Cementerio Civil,http://www.madrid.es/sites/v/index.jsp?vgnextc...,https://datos.madrid.es/egob/kos/Provincia/Mad...,https://datos.madrid.es/egob/kos/Provincia/Mad...,MADRID,28017,AVENIDA DAROCA 90,40.427519,-3.648203,La Empresa Municipal de Servicios Funerarios ...,1,Invierno: todos los días de 8 a 18:30 horas. V...,La gestión integral realizada por parte de los...,Cementerio Civil
2,Cementerio Cristo de El Pardo,http://www.madrid.es/sites/v/index.jsp?vgnextc...,https://datos.madrid.es/egob/kos/Provincia/Mad...,https://datos.madrid.es/egob/kos/Provincia/Mad...,MADRID,28048,CARRETERA CRISTO DE EL PARDO 11,40.519412,-3.788610,Iglesia del Santo Cristo de El Pardo. La Empr...,1,"Martes, jueves, sábado y domingo, de 10 a 17 h...",La gestión integral realizada por parte de los...,Cementerio Cristo de El Pardo
3,Cementerio de Aravaca,http://www.madrid.es/sites/v/index.jsp?vgnextc...,https://datos.madrid.es/egob/kos/Provincia/Mad...,https://datos.madrid.es/egob/kos/Provincia/Mad...,MADRID,28023,CAMINO ZARZUELA 26,40.465747,-3.787073,La Empresa Municipal de Servicios Funerarios ...,1,"Todo el año, de 10 a 17 horas.",La gestión integral realizada por parte de los...,Cementerio de Aravaca
4,Cementerio de Barajas,http://www.madrid.es/sites/v/index.jsp?vgnextc...,https://datos.madrid.es/egob/kos/Provincia/Mad...,https://datos.madrid.es/egob/kos/Provincia/Mad...,MADRID,28042,CARRETERA CEMENTERIO NUEVO 60,40.481991,-3.586915,La Empresa Municipal de Servicios Funerarios ...,1,"Jueves y domingos, de 10 a 17 horas. Día de la...",La gestión integral realizada por parte de los...,Cementerio de Barajas

#### Third API

In [140]:
# https://api.euskadi.eus/directory/entities?subType=PUBLIC_SECTOR&publicSectorScope=AUTONOMY&sector=&lang=SPANISH&fromItemAt=0&pageSize=2000

In [141]:
response = requests.get('https://api.euskadi.eus/directory/entities?subType=PUBLIC_SECTOR&publicSectorScope=AUTONOMY&sector=&lang=SPANISH&fromItemAt=0&pageSize=2000')
print("EUSKADI Status Code:", response.status_code)
results = response.json()

EUSKADI Status Code: 200

In [142]:
# flattened_data = json_normalize(results) # Esto nos sirve para ver las columnas
flattened_data = json_normalize(results['pageItems'])

flattened_data.head()

,oid,id,name,lastUpdate,type.id,type.name,subType.id,subType.name,_links.self.name,_links.self.href,_links.mainEntityOfPage
0,247263C6-A7F7-4F41-A9AC-543C4963F5E5,entity247263C6,Dirección de Tecnología e Innovación,03/08/2022,ENTITY,Entidad,PUBLIC_SECTOR,Entidad Pública,Dirección de Tecnología e Innovación,https://api.euskadi.eus/directory/entities/247...,https://www.euskadi.eus/web01-ejeduki/es/conte...
1,D52E3C04-1562-4B95-9F72-22A77B1634D3,entityD52E3C04,Viceconsejería de Sostenibilidad Ambiental,03/08/2022,ENTITY,Entidad,PUBLIC_SECTOR,Entidad Pública,Viceconsejería de Sostenibilidad Ambiental,https://api.euskadi.eus/directory/entities/D52...,https://www.euskadi.eus/web01-ejeduki/es/conte...
2,773A5D1B-E695-4205-B726-B127C7B5A3FE,entity773A5D1B,Dirección de Asuntos Europeos,03/08/2022,ENTITY,Entidad,PUBLIC_SECTOR,Entidad Pública,Dirección de Asuntos Europeos,https://api.euskadi.eus/directory/entities/773...,https://www.euskadi.eus/web01-ejeduki/es/conte...
3,FD4C9E72-DF4B-4E3E-88A6-E86850E12839,entityFD4C9E72,Dirección de Gabinete,16/09/2022,ENTITY,Entidad,PUBLIC_SECTOR,Entidad Pública,Dirección de Gabinete,https://api.euskadi.eus/directory/entities/FD4...,https://www.euskadi.eus/web01-ejeduki/es/conte...
4,E622DC1F-AFDE-472B-B49F-6295C4E72130,entityE622DC1F,Dirección de Transformación Digital y Emprendi...,03/08/2022,ENTITY,Entidad,PUBLIC_SECTOR,Entidad Pública,Dirección de Transformación Digital y Emprendi...,https://api.euskadi.eus/directory/entities/E62...,https://www.euskadi.eus/web01-ejeduki/es/conte...